# Generated by Django 3.1.3 on 2021-10-15 21:41

import biometrics.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('employment_type', models.CharField(blank=True, choices=[('executive', 'executive'), ('full-timer', 'full-timer'), ('contractual', 'contractual'), ('vendors', 'vendors')], max_length=20)),
                ('employee_code', models.CharField(blank=True, max_length=20)),
                ('reporting_office', models.CharField(blank=True, max_length=15)),
                ('address_2', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('designation', models.CharField(blank=True, max_length=30)),
                ('profile_Pic', models.ImageField(blank=True, upload_to=biometrics.models.path_and_rename, verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
